import 'package:flutter/material.dart';

class Names{
  final List names = [
    [['Ählisi', false], ['Satlyk Jaýlar', false], ['Satlyk söwda we hususy emläkler', false], ['Kireýine jaýlar', false], ['Kireýine ofislar', false], ['Kireýine söwda we hususy emläkler', false], ['Beýleki emläkler', false], ['Kireýine jaý gözleýänler', false]],
    [['Ählisi', false], ['Telefonlar', false], ['Planşetlar', false], ['Öý we ofis telefonlar', false], ['Akylly sagatlar we brasletlar', false], ['Aksessuarlar', false], ['Nauşnikler', false], ['Ätiýäçlyk şaýlary', false]],
    [['Ählisi', false], ['Işgär gözleýänler', false], ['Iş gözleýän', false]],
    [['Ählisi', false], ['Gurluşyk işleri', false], ['Santehnika we elektrika hyzmatlary', false], ['Hojalyk tehnikalary abatlaýyş', false], ['Gurnama işleri we hyzmat', false], ['Tikinçilik we aýakgap hyzmatlary', false], ['Mahabat, poligrafiýa we neşirýat', false], ['Restawrasiýa', false], ['Awtoulaglary abatlaýyş', false], ['Gözellik we saglyk hyzmatlary', false], ['Kompýuter hyzmatlary', false], ['Foto we wideo hyzmatlary', false], ['Hukukçy hyzmatlary', false], ['Buhgalter we audit hyzmatlary', false], ['Terjime hyzmatlary', false], ['Rieltor hyzmatlary', false], ['Tämizlik hyzmatlary',false], ['Bilim berme we türgenleşik', false], ['Iýmit ugry hyzmatlary', false], ['Ulag we daşama hyzmatlary', false], ['Baýramçylyk we dabara hyzmatlary', false], ['Sagat we açar hyzmaty', false], ['Dizaýn we interýer hyzmatlary', false], ['Syýahatçylyk hyzmatlary', false]],
    [['Ählisi', false], ['Ütükler we eşik üçin enjamlar', false], ['Gap-çanak ýuwujy enjamlar', false], ['Holodilnikler we morozilnikler', false], ['Kondisionerlar we wentilýatorlar', false], ['Iýmit taýýarlaýjy enjamlar', false], ['Içgileri taýýarlaýjy enjamlar', false], ['Kulerlar we suw filterlar', false], ['Tozan sorujylar we bug bilen arassalaýyjylar', false], ['Kir ýuwujy enjamlar', false], ['Gaz we tok plitalar', false], ['Tikinçilik enjamlar', false], ['Başga harytlar we enjamlar', false], ['Ýyladyjy enjamlar', false]],
    [['Ählisi', false], ['Egin-eşikler', false], ['Oýunjaklar', false], ['Sagatlar we aksessuarlar', false], ['Arabalar', false], ['Çagalar üçin mebel', false], ['Okuw üçin harytlar', false], ['Himiýa we kosmetika', false], ['Çaga iýmiti', false], ['Başgalar', false]],
    [['Ählisi', false], ['Aýakgaplar', false], ['Aksessuarlar', false], ['Matalar', false], ['Altyn-kümüş harytlar', false], ['Balaklar we jynsy balaklar', false], ['Futbolkalar', false], ['Jempirler', false], ['Joraplar, kolgotkalar', false], ['Kelte balaklar', false], ['Koftalar we bluzkalar', false], ['Köýnekler we keteniler', false], ['Kurtkalar, palto, penjekler we ýeňsizler', false], ['Öýmeler, ýaglyklar we şarflar', false], ['Sport geýimler', false], ['Sumkalar we gapjyklar', false], ['Ýörite geýimler', false], ['Ýubkalar', false]],
    [['Ählisi', false], ['Aýakgaplar', false], ['Balaklar we jynsy jalbarlar', false], ['Futbolkalar', false], ['Jempirler', false], ['Joraplar we iç geýimler', false], ['Kelte balaklar', false], ['Köýnekler', false], ['Kurtkalar, palto we penjekler', false], ['Sagatlar we aksessuarlar', false], ['Sport geýimler', false], ['Sumka, portfel we gapjyklar', false], ['Ýörite geýimler', false]],
    [['Ählisi', false], ['Gap-çanak we kuhnýa esbaplary', false] , ['Hojalyk harytlary', false], ['Hojalyk esbaplary', false], ['Yşyklandyrma we lýustralar', false], ['Mebel we interýer', false], ['Haly we tekstil', false], ['Interýer bezegleri', false], ['Ösümlikler we güller', false], ['Perdeler we žalýuzlar', false], ['Kanselariýa harytlary', false], ['Hojalyk himiýa', false], ['Başgalar', false]],
    [['Ählisi', false], ['Saç üçin serişdeler', false] , ['Deri üçin serişdeler', false], ['Tämizlik serişdeler', false], ['Parfumeriýa', false], ['Kosmetika', false], ['Enjamlar we aksessuarlar', false], ['Başgalar', false]],
    [['Ählisi', false], ['Elektronika aksessuarlar', false] , ['Telewizorlar', false], ['Öý kinoteatrlar', false], ['DVD we Blu-ray pleýerlar', false], ['Tunerlar we sputnik antenlar', false], ['Magnitafonlar', false], ['Mikrofonlar', false], ['MP3 pleýerlar', false], ['Audio usilitellar', false], ['Kolonkalar we sabwuferlar', false], ['Başgalar', false]],
    [['Ählisi', false], ['Enjamlar we harytlar', false] , ['Taýýar işläp duran bizneslar', false], ['Önümçilik we iýmit', false]],
    [['Ählisi', false], ['Fotoapparatlar', false] , ['Wideokameralar', false], ['Kamera gözegçilik', false], ['Obýektiwler', false], ['Foto-Çyralar', false], ['Aksesuarlar', false], ['Saklaýjylar we stabilizatorlar', false], ['Başgalar', false]],
    [['Ählisi', false], ['Goýunlar we geçiler', false] , ['Sygyrlar we öküzler', false], ['Düýeler', false], ['Guşlar', false], ['Güjükler', false], ['Pişikler', false], ['Balyklar', false], ['Gemrijiler', false], ['Beýleki haýwanlar', false], ['Haýwanlar üçin harytlar', false]],
    [['Ählisi', false], ['Noutbuklar', false] , ['Kompyuterlar', false], ['Monitorlar', false], ['Klawiatura we syçanjyk', false], ['Printerler we skanerler', false], ['Kartridžlar we tonerlar', false], ['Set enjamlary', false], ['Kompýuter şaýlary', false], ['Žostkiý disk we fleşkalar', false], ['Web kameralar', false], ['Aksesuarlar', false], ['Programmalar', false], ['Jostiklar', false], ['Oýun pristawkalar', false]],
    [['Ählisi', false], ['Gapylar', false] , ['Penjireler', false], ['Pollar', false], ['Potoloklar', false], ['Oboýlar', false], ['Gurluşuk harytlar', false], ['Elektrika', false], ['Santehnika we suw üpjün etme', false], ['Gyzdyrma we howalandyrma', false], ['Gorag we howpsuzluk enjamlar', false], ['Elektrika enjamlar', false], ['El Instrumentler', false],['Başgalar', false]],
    [['Ählisi', false], ['Sport harytlar', false] , ['Dynç alyş we syýahat', false], ['Elde elin ýasalan (Handmade)', false], ['Kino we kinoteatr', false], ['Kitaplar we žurnallar', false], ['Oýunlar', false], ['Saz we saz enjamlary', false], ['Sport egin-eşik', false], ['Sport enjamlar', false], ['Tigirler, samokatlar we skuterlar', false]],
    [['Ählisi', false], ['Enjamlar', false] , ['Ösümlikler', false], ['Tohumlar', false], ['Dökünler', false], ['Başgalar', false]],
    [['Ählisi', false], ['Ýiten', false], ['Tapylan', false]],
    [['Ählisi', false], ['Başgalar', false]],
  ];

  final List cities = [
    [['Ählisi', false], ['Arzuw', false], ['Atatürk köç.', false], ['"Altyn Asyr" Gündogar bazary (Jygyllyk)', false], ['Arçabil şaýoly', false], ['Bagyr', false], ['Berzeňňi', false], ['Bekrewe', false], ['Bedew', false], ['Podwoýski köç. (Bitarap Türkmenistan şaýoly)', false], ['Büzmeýin', false], ['Büzmeýin GRES', false], ['Çandybil şaýoly', false], ['WDNH Söwda Merkezi', false], ['1 mkr', false], ['2 mkr', false], ['3 mkr', false], ['4 mkr', false], ['5 mkr', false], ['6 mkr', false], ['8 mkr', false], ['9 mkr', false], ['10 mkr', false], ['11 mkr', false], ['30 mkr', false], ['Howdan "A"', false], ['Howdan "B"', false], ['Howdan "B"', false], ['Türkmenbaşy şaýoly', false], ['Aýtakow (Oguzhan köç.)', false], ['12-nji tapgyr (Sowhozny köç.)', false], ['15-nji tapgyr', false], ['Moskowskiý köç.', false], ['Nebitgaz', false], ['Olimpiýa şäherçesi', false], ['Sowetskiý köç.', false], ['Garadamak', false], ['Garadamak şor', false], ['Gökje', false], ['G.Kuliýew köç.', false], ['Gurtly', false], ['Dosaaf', false], ['Kim raýon', false], ['Köpetdag şaýoly', false], ['Köşi', false], ['Parahat 1', false], ['Parahat 2', false], ['Parahat 3', false], ['Parahat 4', false], ['Parahat 5', false], ['Parahat 6', false], ['Parahat 7', false], ['Parahat 8', false], ['Gagarin köç.', false],],
    [['Ählisi', false], ['Ak bugdaý etraby', false],],
    [['Ählisi', false], ['Magtymguly', false],],
    [['Ählisi', false], ['Ýolöten', false],],
    [['Ählisi', false], ['Darganata', false],],
    [['Ählisi', false], ['Akdepe', false],],
  ];
}